### PR TITLE
Develop gsg2

### PR DESCRIPTION
**Pull request by halsaphi**
PR to start the merge process for the structural changes and getting started guide changes in the develop-GSG2 branch to the develop branch.

### CODE REVIEW

**Comment by halsaphi** [comment]
re - docs/05_community-developer-tools/index.md - I have worked through this with Angus so think an 'ours' merge would be ok.

**Comment by halsaphi** [comment]
Current plan is to merge develop and develop-GSG2 on my machine. Any thoughts?

Also any comment . knowledge about changes to:

docs/01_overview/02_core_concepts.md
docs/02_getting-started/03_smart-contract-development/01_hello-world.md
docs/02_getting-started/03_smart-contract-development/03_understanding-ABI-files.md
docs/02_getting-started/03_smart-contract-development/06_adding-inline-actions.md

**Comment by halsaphi** [comment]
git diff develop:docs/01_overview/02_core_concepts.md develop-GSG2:docs/20_introduction-to-eosio/20_core_concepts.md

git diff develop:docs/02_getting-started/03_smart-contract-development/01_hello-world.md develop-GSG2:docs/40_smart-contract-guides/10_hello-world.md

git diff develop:docs/02_getting-started/03_smart-contract-development/03_understanding-ABI-files.md develop-GSG2:docs/40_smart-contract-guides/30_understanding-ABI-files.md

git diff develop:docs/02_getting-started/03_smart-contract-development/06_adding-inline-actions.md develop-GSG2:docs/40_smart-contract-guides/60_adding-inline-actions.md

In all cases I would recommend a merge based on "ours"

**Comment by iamveritas** [comment]
> Current plan is to merge develop and develop-GSG2 on my machine. Any thoughts?

sounds good to me.

**Comment by iamveritas** [comment]
one observation for a follow up (clean up maybe) PR/task:
I noticed a few `## What's Next` sections that are gone (not replaced by anything), it could be that indeed they are not needed anymore or that they were deleted and forgotten to be replaced.

**Comment by iamveritas** [comment]
> Also any comment . knowledge about changes to:
Looks good to me.

**Review by iamveritas — APPROVED** [review]

**Comment by halsaphi** [comment]
> one observation for a follow up (clean up maybe) PR/task:
> I noticed a few `## What's Next` sections that are gone (not replaced by anything), it could be that indeed they are not needed anymore or that they were deleted and forgotten to be replaced.

These were consciously removed and may be added in again later once "what is next" is determined

**Pull request merged**
