### PR TITLE
docs: updated tutorial code to match source files, and added tictacto…

### PR DESCRIPTION
**Pull request by nuwanwre**
Thanks for the tutorials!

A couple of revisions to the tictactoe tutorial.

1. **Adding the creation of smart contract account `tictactoe`.**
   In this [tutorial](https://developers.eos.io/welcome/latest/tutorials/tic-tac-toe-game-smart-contract-single-node), the latter cleos commands assume that the developer has deployed the smart contract under the account `tictactoe`. But, the preceding section instructs the developer to deploy the smart constract under the account of `host`. To lessen the confusion, I've added another create account section for `tictactoe` smart contract, and updated the relevant contract deployment to be under `tictactoe`.
  This should also address #305.

2. **Updated sample code on the doc**
   In both tutorials for Single Node and Testnet, the code samples for `tictactoe.hpp` has the class name and the constructor as `TicTacToe`. But the header file follows the naming of `tictactoe`. To address this issue, the in the code samples, the class name and the constructor was updated from `TicTacToe` -> `tictactoe`, as per reference [here](https://github.com/EOSIO/welcome/blob/release/2.0.x/src/tictactoe/tictactoe.cpp). In addition, addressed some changes mentioned in #308.

@halsaphi, would like to get some feedback on 1. since I don't want the revisions to deviate from the original direction you were planning for the tutorial. Thanks!

### CODE REVIEW

**Review by halsaphi — COMMENTED** [review]
Hi,
 
Re 1. Using three accounts makes sense, though will require some additional cosmetic changes to the text.
Re 2. Good spots ... though some additional fixes are required:
2 x  IsEmptyCell rather than isEmptyCell in the sample code - in both tutorial versions

I can make these additional changes after merging or request changes to this PR - do you have a preference?

**Comment by nuwanwre** [comment]
I will update the `IsEmptyCell` -> `isEmptyCell` occurrences for the tutorials, and push one more commit. For 1, is it okay if I leave it as it in the current state of this PR? I feel like it's better if you make the additional changes since you have the original idea of how the tutorial should flow.

**Comment by nuwanwre** [comment]
Updated the PR!

**Review by halsaphi — APPROVED** [review]
Great, and thanks.

I'll add some additional changes to support using three accounts after this has been merged.

**Pull request merged**
