### PR TITLE
add chain controller signals

### PR DESCRIPTION
**Pull request by iamveritas**
add chain controller signals
resolves https://github.com/EOSIO/eos/issues/7213

### CODE REVIEW

**Comment by nguyendoanh99** [comment]
Không đọc được

**Comment by nguyendoanh99** [comment]
Tôi không đọc được chữ trên trình duyệt mất 6 h với cái đó không có dịch tôi chịu thua

**Comment by nguyendoanh99** [comment]
Trả nó về như cũ thì tốt tôi dùng quen goodle cảm ơn các bạn vì ý tốt nhưng tôi vã mồ hôi 😰😓😄😄😄

**Comment by iamveritas** [comment]
@lparisc I think you are a bit confused? on my local tests those titles look great.
also the issue you are pointing out it is talking about links in titles related with back ticks.

see how they will render here:
image

**Comment by iamveritas** [comment]
ah, I see what you mean, you mean the links from the right bottom navigation will not render correctly, they were almost not visible and they escaped me.
so I was the confused one! :)
thanks for pointing it out.

**Pull request merged**
